### ISSUE TITLE
[BUG] MagiBridge doesn't work with Nucleus-2.3.2

### ISSUE THREAD

**Issue by poqdavid** [Eufranio/MagiBridge#216]
Today just updated the server and MagiBridge doesn't work anymore a lot of functions broke

```
java.lang.NoClassDefFoundError: io/github/nucleuspowered/nucleus/api/events/NucleusAFKEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_282]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_282]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_282]
	at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:248) ~[SpongeEventManager.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:315) ~[SpongeEventManager.class:1.12.2-2838-7.3.0]
	at com.magitechserver.magibridge.MagiBridge.registerListeners(MagiBridge.java:286) ~[MagiBridge.class:?]
	at com.magitechserver.magibridge.MagiBridge.lambda$init$12(MagiBridge.java:219) ~[MagiBridge.class:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) ~[?:1.8.0_282]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.ClassNotFoundException: io.github.nucleuspowered.nucleus.api.events.NucleusAFKEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	... 19 more
Caused by: java.lang.NullPointerException
```

spongeforge-1.12.2-2838-7.3.0
Nucleus-2.3.2-MC1.12.2-SpongeAPI7.3`

**Comment by poqdavid** [comment]
Sorry missed the version so i am just closing this
